# KEYBINDINGS
# alt-f3 (highlight word, highlight all matches)
# ctrl-shift-d (duplicate line)
# ctrl-click (write in multiple places)
# ctrl-left/right (skip to beginning/end of subword)
# ctrl-up/down (move current line up/down)
# ctrl-d (highlight word, highlight matches) (ctrl-u unselects)
# ctrl-/ (comment line) (comment highlighted lines)
# ctrl-backspace (delete to beginning of subword)
# ctrl-l (select line)
# ctrl-enter (jump to new line)
# `div.myClass`-tab (emmet) (<div class="myClass"></div>)
# `div.myClass`-tab (jsx emmet) (<div className="myClass"></div>) (https:#gist.github.com/mxstbr/361ddb22057f0a01762240be209321f0)
# ctrl-comma (open preferences)
# ctrl-k + ctrl-u (selection to uppercase)