[package]
name = "nickel-example"
version = "0.1.0"
edition = "2018"

[dependencies]
nickel = "*"
hyper = "0.14"
tokio = { version = "1.11.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.59"
