[package]
name = "redis-notes"
version = "0.1.0"
edition = "2021"

[dependencies]
redis = { version = "0.21.2", features = ["tokio-comp"] }
tokio = { version = "1.12.0", features = ["full"] }
async-trait = "0.1.51"

