# ---
# variables
# ---

OUTPUT="main"

# --- 
# commands
# --- 

.PHONY: build run

build: 
	@ g++ main.cpp -o $(OUTPUT) -std=c++2a

run:
	@ ./main

# --- 
# compiler
# --- 

# c++11
# g++ main.cpp -o $(OUTPUT) -std=c++11

# c++20 (working version)
# g++ main.cpp -o $(OUTPUT) -std=c++2a