[package]
name = "sqlx-notes"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.7.4", features = [
    "postgres",
    "runtime-async-std-native-tls",
    "migrate",
    "uuid",
    "chrono",
] }
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1.12.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1.51"
anyhow = "1.0.45"
