[package]
name = "reqwest-notes"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.12.0", features = ["full"] }
reqwest = { version = "0.11.6", features = ["json"]}
chrono = { version = "0.4", features = ["serde"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
uuid = { version = "0.8.2", features = ["serde", "v4"]}
anyhow = "1.0.45"

[[bin]]
name = "main"
path = "src/main.rs"

