[package]
name = "flate2-notes"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
flate2 = { version = "1.0.17", features = ["zlib"], default-features = false }
# flate2 = "1.0"

[[bin]]
name = "main"
path = "src/main.rs"

