# ---
# variables
# ---

# TODO

# --- 
# commands
# --- 

.PHONY: dev dev-build build

# creates (and runs) executable in ./target/debug/<project-name>
dev: 
	@cargo run

# creates executable in ./target/debug/<project-name>
dev-build: 
	@cargo build

# creates executable in ./target/release/<project-name>
build: 
	@cargo build --release

