[package]
name = "basics"
version = "0.1.0"
edition = "2018"

[dependencies]

[[bin]]
name = "main"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html