# ---
# variables
# ---

# None

# ---
# commands (start/build)
# ---

.PHONY: install dev run run-example \

install:
	npm i

dev:
	npm run dev

run:
	npm start

# ---
# commands (example)
# ---

run-example:
	npm run run-example